name: Hackathon test
on:
  pull_request:
    branches:
     - main
  workflow_dispatch:
  #push:
   # branches:
    #  - main
permissions:
  id-token: write # Enable OIDC token request      
  contents: read
jobs:
  fmt-validate:
    name: check terraform Formatting and validation
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::825765394891:role/oidc_connect_role
          aws-region: ap-south-1
     # - name: Test aws access
      #  run: aws sts get-caller-identity
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      - name: Terraform Forat Check
        run: terraform fmt -check -recurcive
      - name: terraform Init
        run: terraform init
      - name: terraform Validate
        run: terraform validate
      
